apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aimanifestanalyses.ai.example.com
spec:
  group: ai.example.com
  scope: Namespaced
  names:
    plural: aimanifestanalyses
    singular: aimanifestanalysis
    kind: AIManifestAnalysis
    shortNames:
      - ama
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            kind:
              type: string
              description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            metadata:
              type: object
            spec:
              type: object
              properties:
                manifest:
                  type: string
                  description: "Manifest is the Kubernetes manifest to be analyzed."
              required:
                - manifest
            status:
              type: object
              properties:
                analysisResult:
                  type: string
                  description: "AnalysisResult is the result of the manifest analysis."
                error:
                  type: string
                  description: "Error stores any error messages during the analysis."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Manifest
          type: string
          jsonPath: .spec.manifest
          description: The Kubernetes manifest to be analyzed
        - name: Result
          type: string
          jsonPath: .status.analysisResult
        - name: Error
          type: string
          jsonPath: .status.error
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
